const mongoose = require('mongoose');

const todoSchema = new mongoose.Schema({
    uid: {
        type: String,
        required: [true, 'UID not provided'],
        ref: 'User',
    },

    // Additionally, userId auto-generated by mongoose
    // userId: {
    //     //mongoose.Schema.ObjectId and mongoose.Schema.Types.ObjectId refer to the exact same thing.
    //     type: mongoose.Schema.Types.ObjectId,
    //     required: [true, 'Please provide user'],
    //     ref: 'User',
    // },

    title: {
        type: String,
    },
});
