const mongoose = require('mongoose');

const todoSchema = new mongoose.Schema(
    {
        uid: {
            type: String,
            required: [true, 'UID not provided'],
            ref: 'User',
        },

        // Additionally, userId auto-generated by mongoose
        /*  mongoose.Schema.ObjectId and mongoose.Schema.Types.ObjectId refer to the exact same thing. */
        // userId: {
        //     type: mongoose.Schema.Types.ObjectId,
        //     required: [true, 'Please provide user'],
        //     ref: 'User',
        // },

        title: {
            type: String,
        },

        completed: {
            type: Boolean,
            default: false,
        },
        expireAt: {
            type: Date,
        },
    },
    // If you set timestamps: true, Mongoose will add two properties of type Date to your schema:
    //createdAt: a date representing when this document was created
    //updatedAt: a date representing when this document was last updated
    { timestamps: true }
);

todoSchema.index({ expireAt: 1 }, { expireAfterSeconds: 0 });

module.exports = mongoose.model('Todo', todoSchema);
